
export interface ModelEntry {
  id: number;
  symbol: string;
  name: string;
  category: 'Psychology' | 'Math' | 'Physics' | 'Chemistry' | 'Biology' | 'Engineering' | 'Economics' | 'Decision';
  founder: string;
  brief: string;
}

export const MENTAL_MODELS_100: ModelEntry[] = [
  {id: 1, symbol: "In", name: "激励导向偏差", category: "Psychology", founder: "Munger", brief: "奖励机制决定行为。"},
  {id: 2, symbol: "Li", name: "喜爱倾向", category: "Psychology", founder: "Cialdini", brief: "因好感而忽视缺点。"},
  {id: 3, symbol: "Ha", name: "讨厌倾向", category: "Psychology", founder: "Traditional", brief: "因反感而忽视优点。"},
  {id: 4, symbol: "Du", name: "避免怀疑", category: "Psychology", founder: "Evolutionary", brief: "急于消除不确定性。"},
  {id: 5, symbol: "Ic", name: "避免不一致性", category: "Psychology", founder: "Munger", brief: "抗拒改变既有观念。"},
  {id: 6, symbol: "Cu", name: "好奇心倾向", category: "Psychology", founder: "Traditional", brief: "探索未知的本能。"},
  {id: 7, symbol: "Kf", name: "康德式公平", category: "Psychology", founder: "Kant", brief: "对绝对公平的执着。"},
  {id: 8, symbol: "Ej", name: "妒忌倾向", category: "Psychology", founder: "Munger", brief: "驱动世界的隐形力量。"},
  {id: 9, symbol: "Rt", name: "回馈倾向", category: "Psychology", founder: "Cialdini", brief: "以德报德，以牙还牙。"},
  {id: 10, symbol: "Ma", name: "简单联想影响", category: "Psychology", founder: "Pavlov", brief: "中性事物的错误挂钩。"},
  {id: 11, symbol: "Pd", name: "心理否认", category: "Psychology", founder: "Freud", brief: "扭曲现实以逃避痛苦。"},
  {id: 12, symbol: "Sr", name: "自视过高", category: "Psychology", founder: "Traditional", brief: "禀赋效应与过度自信。"},
  {id: 13, symbol: "Ot", name: "过度乐观", category: "Psychology", founder: "Traditional", brief: "违背概率的盲目期盼。"},
  {id: 14, symbol: "Ds", name: "被剥夺超级反应", category: "Psychology", founder: "Munger", brief: "极度厌恶损失。"},
  {id: 15, symbol: "Sp", name: "社会认同", category: "Psychology", founder: "Cialdini", brief: "观察他人决定行动。"},
  {id: 16, symbol: "Cm", name: "对比错误反应", category: "Psychology", founder: "Traditional", brief: "温水煮青蛙效应。"},
  {id: 17, symbol: "St", name: "压力影响", category: "Psychology", founder: "Traditional", brief: "压力下认知功能下线。"},
  {id: 18, symbol: "Av", name: "易得性偏差", category: "Psychology", founder: "Kahneman", brief: "误把鲜活当成高频。"},
  {id: 19, symbol: "Ul", name: "不用就忘", category: "Psychology", founder: "Traditional", brief: "技能不练习就会退化。"},
  {id: 20, symbol: "Dm", name: "化学物质误导", category: "Psychology", founder: "Biology", brief: "生理层面的认知扭曲。"},
  {id: 21, symbol: "Sm", name: "衰老错误影响", category: "Psychology", founder: "Biology", brief: "认知灵活性的自然减退。"},
  {id: 22, symbol: "Am", name: "权威错误影响", category: "Psychology", founder: "Milgram", brief: "盲目服从领袖。"},
  {id: 23, symbol: "Tw", name: "废话倾向", category: "Psychology", founder: "Social", brief: "无实质内容的喋喋不休。"},
  {id: 24, symbol: "Rr", name: "重视理由", category: "Psychology", founder: "Cialdini", brief: "对“因为”的本能顺从。"},
  {id: 25, symbol: "Lz", name: "Lollapalooza", category: "Psychology", founder: "Munger", brief: "多重偏差共振爆发。"},
  {id: 26, symbol: "Pr", name: "概率思维", category: "Math", founder: "Fermat", brief: "评估未来的预期价值。"},
  {id: 27, symbol: "Pc", name: "排列组合", category: "Math", founder: "Pascal", brief: "理解复杂状态的基础。"},
  {id: 28, symbol: "Ae", name: "代数等价", category: "Math", founder: "Jacobi", brief: "转化复杂问题。"},
  {id: 29, symbol: "Rn", name: "随机性", category: "Math", founder: "Taleb", brief: "无因果的随机游走。"},
  {id: 30, symbol: "Sp", name: "随机过程", category: "Math", founder: "Traditional", brief: "随时间演变的系统。"},
  {id: 31, symbol: "Cp", name: "复利", category: "Math", founder: "Einstein", brief: "指数增长的力量。"},
  {id: 32, symbol: "Mz", name: "乘以零效应", category: "Math", founder: "Logic", brief: "关键环节失效则全盘皆输。"},
  {id: 33, symbol: "Ch", name: "流失率", category: "Math", founder: "Business", brief: "存量系统的自然衰减。"},
  {id: 34, symbol: "Ln", name: "大数定律", category: "Math", founder: "Bernoulli", brief: "样本量大则收敛于均值。"},
  {id: 35, symbol: "Nd", name: "正态分布", category: "Math", founder: "Gauss", brief: "描述独立随机变量。"},
  {id: 36, symbol: "Pl", name: "幂律分布", category: "Math", founder: "Pareto", brief: "少数节点拥有多数价值。"},
  {id: 37, symbol: "Ft", name: "厚尾分布", category: "Math", founder: "Taleb", brief: "极端风险发生的可能。"},
  {id: 38, symbol: "Bu", name: "贝叶斯更新", category: "Math", founder: "Bayes", brief: "根据证据动态调整信心。"},
  {id: 39, symbol: "Rm", name: "均值回归", category: "Math", founder: "Galton", brief: "极端表现必向平均靠拢。"},
  {id: 40, symbol: "Om", name: "数量级", category: "Math", founder: "Fermi", brief: "搞对小数点的位置。"},
  {id: 41, symbol: "Cm", name: "临界点", category: "Physics", founder: "Nuclear", brief: "性质突变的门槛。"},
  {id: 42, symbol: "Td", name: "热力学定律", category: "Physics", founder: "Clausius", brief: "能量守恒与熵增。"},
  {id: 43, symbol: "Rg", name: "重正化群", category: "Physics", founder: "Wilson", brief: "不同尺度下的规律。"},
  {id: 44, symbol: "Rf", name: "作用力/反作用力", category: "Physics", founder: "Newton", brief: "每一个动作都有后果。"},
  {id: 45, symbol: "Vc", name: "速度矢量", category: "Physics", founder: "Newton", brief: "方向比速率更重要。"},
  {id: 46, symbol: "Rl", name: "相对论", category: "Physics", founder: "Einstein", brief: "没有绝对的参照系。"},
  {id: 47, symbol: "Ae", name: "活化能", category: "Chemistry", founder: "Arrhenius", brief: "引发反应的最小能量。"},
  {id: 48, symbol: "Ca", name: "催化剂", category: "Chemistry", founder: "Traditional", brief: "降低门槛，加速反应。"},
  {id: 49, symbol: "It", name: "惯性", category: "Physics", founder: "Newton", brief: "保持原有状态的阻力。"},
  {id: 50, symbol: "Lv", name: "杠杆作用", category: "Physics", founder: "Archimedes", brief: "放大输入力的工具。"},
  {id: 51, symbol: "Ns", name: "自然选择", category: "Biology", founder: "Darwin", brief: "环境淘汰不适应者。"},
  {id: 52, symbol: "Rq", name: "红皇后效应", category: "Biology", founder: "Leigh", brief: "必须奔跑以留在原地。"},
  {id: 53, symbol: "Cs", name: "合作互惠", category: "Biology", founder: "Axelrod", brief: "共生是生存的高级策略。"},
  {id: 54, symbol: "Me", name: "能量最小化", category: "Biology", founder: "Biology", brief: "倾向于阻力最小的路径。"},
  {id: 55, symbol: "Ad", name: "适应性", category: "Biology", founder: "Darwin", brief: "为生存而改变特征。"},
  {id: 56, symbol: "Rp", name: "复制本能", category: "Biology", founder: "Dawkins", brief: "基因自我延续的欲望。"},
  {id: 57, symbol: "Hi", name: "等级秩序", category: "Biology", founder: "Traditional", brief: "群体内的支配结构。"},
  {id: 58, symbol: "Sp", name: "自我保存", category: "Biology", founder: "Biology", brief: "最底层的生存指令。"},
  {id: 59, symbol: "Rs", name: "奖赏寻求", category: "Biology", founder: "Biology", brief: "多巴胺驱动的行为。"},
  {id: 60, symbol: "Ex", name: "利他转用", category: "Biology", founder: "Gould", brief: "特征的意外功能挪用。"},
  {id: 61, symbol: "Et", name: "灭绝", category: "Biology", founder: "Traditional", brief: "当环境变迁超过适应力。"},
  {id: 62, symbol: "Es", name: "生态系统", category: "Biology", founder: "Tansley", brief: "复杂的相互作用网络。"},
  {id: 63, symbol: "Ni", name: "生存利基", category: "Biology", founder: "Grinnell", brief: "特定位置的竞争优势。"},
  {id: 64, symbol: "Rd", name: "备份系统", category: "Engineering", founder: "Engineering", brief: "预防单点故障。"},
  {id: 65, symbol: "Ms", name: "安全边际", category: "Engineering", founder: "Graham", brief: "应对不可知的余量。"},
  {id: 66, symbol: "Fb", name: "反馈循环", category: "Engineering", founder: "Wiener", brief: "系统自我调节。"},
  {id: 67, symbol: "Ay", name: "合金效应", category: "Engineering", founder: "Munger", brief: "组合优于单一元素。"},
  {id: 68, symbol: "Bn", name: "瓶颈", category: "Engineering", founder: "Goldratt", brief: "限制整体的窄项。"},
  {id: 69, symbol: "Bp", name: "断裂点", category: "Engineering", founder: "Engineering", brief: "压力失效的临界值。"},
  {id: 70, symbol: "Oc", name: "机会成本", category: "Economics", founder: "Wieser", brief: "放弃的最高价值。"},
  {id: 71, symbol: "Sd", name: "供需", category: "Economics", founder: "Smith", brief: "市场平衡的基础力。"},
  {id: 72, symbol: "Dm", name: "边际效用递减", category: "Economics", founder: "Gossen", brief: "投入越多回报增量越少。"},
  {id: 73, symbol: "Pp", name: "二八法则", category: "Economics", founder: "Pareto", brief: "关键少数决定多数。"},
  {id: 74, symbol: "Gl", name: "格雷欣定律", category: "Economics", founder: "Gresham", brief: "劣币驱逐良币。"},
  {id: 75, symbol: "Ne", name: "网络效应", category: "Economics", founder: "Metcalfe", brief: "用户增多，价值激增。"},
  {id: 76, symbol: "Tc", name: "公地悲剧", category: "Economics", founder: "Hardin", brief: "个体理性致集体灾难。"},
  {id: 77, symbol: "Ca", name: "比较优势", category: "Economics", founder: "Ricardo", brief: "分工与贸易的基石。"},
  {id: 78, symbol: "Cd", name: "创造性破坏", category: "Economics", founder: "Schumpeter", brief: "进化的代价是毁灭。"},
  {id: 79, symbol: "Mm", name: "市场先生", category: "Economics", founder: "Graham", brief: "情绪化的市场报价。"},
  {id: 80, symbol: "Ab", name: "套利", category: "Economics", founder: "Traditional", brief: "利用差价抹平不平衡。"},
  {id: 81, symbol: "Sc", name: "稀缺效应", category: "Economics", founder: "Cialdini", brief: "物以稀为贵。"},
  {id: 82, symbol: "Sm", name: "中场支配", category: "Economics", founder: "Business", brief: "卡住核心议价链。"},
  {id: 83, symbol: "Sz", name: "专业化", category: "Economics", founder: "Smith", brief: "分工提升效率。"},
  {id: 84, symbol: "Ip", name: "知识产权", category: "Economics", founder: "Law", brief: "对无形的临时垄断。"},
  {id: 85, symbol: "Db", name: "复式记账", category: "Economics", founder: "Pacioli", brief: "商业问责的基石。"},
  {id: 86, symbol: "Ut", name: "效用", category: "Economics", founder: "Bernoulli", brief: "主观价值的满足度。"},
  {id: 87, symbol: "Bb", name: "贿赂", category: "Economics", founder: "Traditional", brief: "代理人问题的崩塌。"},
  {id: 88, symbol: "Iv", name: "逆向思维", category: "Decision", founder: "Jacobi", brief: "反过来想以避坑。"},
  {id: 89, symbol: "Fs", name: "可证伪原理", category: "Decision", founder: "Popper", brief: "科学必须能被证伪。"},
  {id: 90, symbol: "Cc", name: "能力圈", category: "Decision", founder: "Buffett", brief: "守住自己的认知边界。"},
  {id: 91, symbol: "Or", name: "奥卡姆剃刀", category: "Decision", founder: "Occam", brief: "简单即正确。"},
  {id: 92, symbol: "Hr", name: "汉隆剃刀", category: "Decision", founder: "Hanlon", brief: "别把愚蠢当恶意。"},
  {id: 93, symbol: "So", name: "二阶思维", category: "Decision", founder: "Marks", brief: "考虑后果的后果。"},
  {id: 94, symbol: "Mt", name: "地图非疆域", category: "Decision", founder: "Korzybski", brief: "模型不等于真实。"},
  {id: 95, symbol: "Te", name: "思维试验", category: "Decision", founder: "Einstein", brief: "大脑里的极限推演。"},
  {id: 96, symbol: "Dn", "name": "邓巴数字", category: "Decision", founder: "Dunbar", brief: "社交规模的生物上限。"},
  {id: 97, symbol: "Tr", "name": "信任", category: "Decision", founder: "Social", brief: "社会运行的润滑剂。"},
  {id: 98, symbol: "Pd", "name": "囚徒困境", category: "Decision", founder: "Nash", brief: "理性竞争的非理性结局。"},
  {id: 99, symbol: "Ni", "name": "叙事本能", category: "Decision", founder: "History", brief: "用故事理解世界的偏好。"},
  {id: 100, symbol: "Le", "name": "林迪效应", category: "Decision", founder: "Taleb", brief: "时间越久，生命力越强。"}
];
